font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
icon-theme=Papirus-Dark
fields=filename,name,generic
password-character=*
filter-desktop=yes

[colors]
# 格式為 RRGGBBAA (最後兩位是透明度)
background=1e1e2eff  # 深色背景
text=cdd6f4ff
match=00ffffff      # 搜尋匹配字改為亮青色
selection=313244ff
selection-text=00ffffff
border=00ffffff      # 邊框改為亮青色

[border]
width=2
radius=10
