general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/tree/Pictures/wallpaper-remove-mhk.png
    # blur_passes = 3 
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
}

# 密碼輸入框
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    # 邊框顏色：亮青色
    outer_color = rgb(0, 255, 255)
    # 內部背景：半透明黑色，透出後面的模糊桌布
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
